### ISSUE TITLE
Metrics not reported to New Relic

### ISSUE THREAD

**Issue by theredcat** [GrahamDumpleton-abandoned/mod_wsgi-metrics#1]
Hi,

I'm trying to install mod_wsgi-metrics with a standard apache installation and i can't get it work.  I've followed the readme on this repo.

Here is the things i've checked :
- The process is running.
- When I strace it, one of the wsgi-metrics threads seems to be pooling /proc/[first apache child PID]/(status|stat|statm)
- The other threads aren't making any informatives syscall so strace won't help. I've put them here anyway : http://pastebin.com/8DEGVhGN
- Here is the lsof on the wsgi proccess : http://pastebin.com/uND8fKvz
- Here is the script I'm using : http://pastebin.com/zksfrYyM
- The host is firewalled for inboud and outbond traffic but I've open 80 and 443 ports from the server to 0.0.0.0/0
- I have this in my Apache error log but this doesn't look like an error? : [Wed Jan 14 14:35:37 2015] [error] mod_wsgi.metrics.newrelic.agent (pid=18459, level=INFO): New Relic platform plugin reporting to 'dam'.
- This is my default vhost configuration (the one with wsgi-metrics) : http://pastebin.com/QAPn3RPF
- This is my main app vhost : http://pastebin.com/kD99HYPC

Do you see anything wrong in these confs?

I don't want to use mod_wsgi-express since I can't found enough documentation/explanations on the interactions between apache and mod_wsgi-express and I'm trying to setup this on a production server.

**Comment by GrahamDumpleton** [comment]
Are you loading mod_status into Apache though and have you enabled extended status.

```
LoadModule status_module modules/mod_status.so
ExtendedStatus On
```

From the host where running this, can you access port 80 on `platform-api.newrelic.com`.

You can use curl to check.

```
$ curl -v platform-api.newrelic.com
* About to connect() to platform-api.newrelic.com port 80 (#0)
*   Trying 50.31.164.164...
* connected
* Connected to platform-api.newrelic.com (50.31.164.164) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8z zlib/1.2.5
> Host: platform-api.newrelic.com
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 0
<
* Connection #0 to host platform-api.newrelic.com left intact
* Closing connection #0
```

It is okay that you get back `400 Bad Request` as we aren't sending a real request and it will complain.

Are you sure there are no other messages about 1 minute after you see:

```
[error] mod_wsgi.metrics.newrelic.agent (pid=18459, level=INFO): New Relic platform plugin reporting to 'dam'.
```

**Comment by theredcat** [comment]
Hi Graham,

I'm not getting any errors in the Apache log, even in Debug level. 

Here is my complete apache log : http://pastebin.com/GSuwTkze

I'm not getting any error message after apache start, even few minutes after start.

**Comment by GrahamDumpleton** [comment]
I am going to have to improve the logging for the plugin, it is rather minimal right now. Will take me a few days to get to it though as trying to get releases of mod_wsgi itself and some other packages out.

**Comment by GrahamDumpleton** [comment]
For the record I have effectively deprecated the New Relic plugin support and will not being putting any more active effort in to it. I will be moving things to use Open Source tools for data collection and reporting instead. Closing this issue at this point.
